name: Build

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04 / Qt 5.15.2
            runs_on: ubuntu-22.04
            host: linux
            qt_version: "5.15.2"
            qt_arch: gcc_64
          - name: Ubuntu 22.04 / Qt 6.6.2
            runs_on: ubuntu-22.04
            host: linux
            qt_version: "6.6.2"
            qt_arch: gcc_64
          - name: Debian 12 / Qt 5.15.2
            runs_on: ubuntu-22.04
            container: debian:12
            host: linux
            qt_version: "5.15.2"
            qt_arch: gcc_64
          - name: Debian 12 / Qt 6.6.2
            runs_on: ubuntu-22.04
            container: debian:12
            host: linux
            qt_version: "6.6.2"
            qt_arch: gcc_64
          - name: macOS / Qt 5.15.2
            runs_on: macos-latest
            host: mac
            qt_version: "5.15.2"
            qt_arch: clang_64
          - name: macOS / Qt 6.6.2
            runs_on: macos-latest
            host: mac
            qt_version: "6.6.2"
            qt_arch: clang_64
          - name: Windows / Qt 5.15.2 (MinGW)
            runs_on: windows-latest
            host: windows
            qt_version: "5.15.2"
            qt_arch: win64_mingw81
          - name: Windows / Qt 6.6.2 (MinGW)
            runs_on: windows-latest
            host: windows
            qt_version: "6.6.2"
            qt_arch: win64_mingw

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup MSYS2 (MinGW64)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
      - name: Install Linux dependencies
        if: matrix.host == 'linux'
        run: |
          set -e
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y build-essential pkg-config freerdp2-dev libwinpr2-dev mesa-common-dev libglu1-mesa-dev libegl1 libxkbcommon0
          else
            apt-get update
            apt-get install -y build-essential pkg-config freerdp2-dev libwinpr2-dev mesa-common-dev libglu1-mesa-dev libegl1 libxkbcommon0
          fi
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.qt_arch }}
          modules: qtcharts
          install-deps: false
          cache: true
      - name: Add MSYS2 MinGW64 to PATH
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo C:\msys64\mingw64\bin>> %GITHUB_PATH%
      - name: Show qmake version
        run: qmake -v
      - name: Configure project (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          cd build
          qmake ../src/xenadminqt.pro
      - name: Configure project (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          if not exist build mkdir build
          cd build
          qmake ..\src\xenadminqt.pro
      - name: Build project (Unix)
        if: runner.os != 'Windows'
        run: |
          cd build
          if [ "$RUNNER_OS" = "macOS" ]; then
            make -j"$(sysctl -n hw.logicalcpu)"
          else
            make -j"$(nproc)"
          fi
      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd build
          mingw32-make -j%NUMBER_OF_PROCESSORS%
