name: Build

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu 22.04 / Qt 5.15.2
            runs_on: ubuntu-22.04
            host: linux
            qt_version: "5.15.2"
            qt_arch: gcc_64
          - name: Ubuntu 22.04 / Qt 6.6.2
            runs_on: ubuntu-22.04
            host: linux
            qt_version: "6.6.2"
            qt_arch: gcc_64
          - name: Debian 12 / Qt 5.15.2
            runs_on: ubuntu-22.04
            container: debian:12
            host: linux
            qt_version: "5.15.2"
            qt_arch: gcc_64
          - name: Debian 12 / Qt 6.6.2
            runs_on: ubuntu-22.04
            container: debian:12
            host: linux
            qt_version: "6.6.2"
            qt_arch: gcc_64
          - name: macOS / Qt 5.15.2
            runs_on: macos-latest
            host: mac
            qt_version: "5.15.2"
            qt_arch: clang_64
          - name: macOS / Qt 6.6.2
            runs_on: macos-latest
            host: mac
            qt_version: "6.6.2"
            qt_arch: clang_64

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Linux dependencies
        if: matrix.host == 'linux'
        run: |
          set -e
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y pkg-config freerdp2-dev libwinpr2-dev
          else
            apt-get update
            apt-get install -y pkg-config freerdp2-dev libwinpr2-dev
          fi
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          host: ${{ matrix.host }}
          target: desktop
          arch: ${{ matrix.qt_arch }}
          modules: qtcharts
          install-deps: false
          cache: true
      - name: Show qmake version
        run: qmake -v
      - name: Configure project
        run: |
          mkdir -p build
          cd build
          qmake ../src/xenadminqt.pro
      - name: Build project
        run: |
          cd build
          if [ "$RUNNER_OS" = "macOS" ]; then
            make -j"$(sysctl -n hw.logicalcpu)"
          else
            make -j"$(nproc)"
          fi
